### PR TITLE
Added Docker image badge & missing punctuation's

### PR DESCRIPTION
**Pull request by sumitkharche**
## Changes
- Added Docker Image badge
- Corrected grammar
- Added missing punctuation's

### CODE REVIEW

**Comment by sumitkharche** [comment]
@SuperSaiyan-God Thanks for approving changes.

**Comment by sumitkharche** [comment]
@SuperSaiyan-God Although you have approved the changes, it is showing that  review is required. Can you please again approve this PR if the changes still looks good to you?

**Comment by sumitkharche** [comment]
@SuperSaiyan-God Any updates on this PR?

**Comment by lizrice** [comment]
Fixed conflict in #55

**Pull request closed without merging**
